language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - cd unittest
  - python -m coverage run test_neuralNetwork.py
after_success:
  - coveralls
